### ISSUE TITLE
NoSuchMethodError: sbt.package$.singleFileJsonFormatter()Lsjsonnew/JsonFormat

### ISSUE THREAD

**Issue by blast-hardcheese** [guardrail-dev/sbt-guardrail#62]
```
sbt:guardrail-sample-akka-http> compile
[info] Updating {file:/Users/dstewart/Documents/guardrail-sample-akka-http/}guardrail-sample-akka-http...
[info] Done updating.
[error] java.lang.NoSuchMethodError: sbt.package$.singleFileJsonFormatter()Lsjsonnew/JsonFormat;
[error]         at com.twilio.guardrail.sbt.GuardrailAnalysis$.<init>(GuardrailAnalysis.scala:18)
[error]         at com.twilio.guardrail.sbt.GuardrailAnalysis$.<clinit>(GuardrailAnalysis.scala)
[error]         at com.twilio.guardrail.sbt.AbstractGuardrailPlugin.cachedGuardrailTask(AbstractCodegenPlugin.scala:151)
[error]         at com.twilio.guardrail.sbt.AbstractGuardrailPlugin.$anonfun$projectSettings$3(AbstractCodegenPlugin.scala:175)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (compile:guardrail) java.lang.NoSuchMethodError: sbt.package$.singleFileJsonFormatter()Lsjsonnew/JsonFormat;
[error] Total time: 1 s, completed May 16, 2020 12:00:24 PM
sbt:guardrail-sample-akka-http>
```

Investigating a workaround, but this is with sbt 1.0.4 and sbt-guardrail 0.57.2

**Comment by blast-hardcheese** [comment]
1.3.10 and 0.57.2 works...

**Comment by blast-hardcheese** [comment]
1.2.0 and 0.57.2 does not work
1.3.0 and 0.57.2 does work

this leads me to believe that sbt-guardrail is compiled against the 1.3.x SBT API, and previous versions of SBT would be incompatible, which is regrettable.
